services:
  receiver:
    build:
      context: receiver
      dockerfile: Dockerfile
    environment:
      LOG_FILE_NAME: receiver.log
    volumes:
      - ./config:/config
      - ./logs/receiver.log:/app/receiver.log
    depends_on:
      - kafka
    ports:
      - "8080:8080"
  storage:
    build:
      context: storage
      dockerfile: Dockerfile
    environment:
      LOG_FILE_NAME: storage.log
    volumes:
      - ./config:/config
      - ./logs/storage.log:/app/storage.log
    depends_on:
      - kafka
      - db
  processing:
    build:
      context: processing
      dockerfile: Dockerfile
    environment:
      LOG_FILE_NAME: processing.log
    volumes:
      - ./config:/config
      - ./logs/processing.log:/app/processing.log
    depends_on:
      - storage
    ports:
      - "8100:8100"
  analyzer:
    build:
      context: analyzer
      dockerfile: Dockerfile
    environment:
      LOG_FILE_NAME: analyzer.log
    volumes:
      - ./config:/config
      - ./logs/analyzer.log:/app/analyzer.log
    depends_on:
      - kafka
    ports:
      - "8120:8120"
  db:
    image: mysql
    container_name: 3855_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 28cjo$9*khgusj
      MYSQL_USER: Ian_admin
      MYSQL_PASSWORD: helpme
      MYSQL_DATABASE: 3855_project
    volumes:
      - my-db:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    restart: unless-stopped
    volumes:
      - zoo-data:/data
      - zoo-logs:/datalog  
  
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    restart: unless-stopped
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - kafka-data:/kafka
      - kafka-logs:/var/log/kafka
    depends_on:
      - "zookeeper"

volumes:
  my-db:
  zoo-data:
  zoo-logs:
  kafka-data:
  kafka-logs: