services:
  db:
    image: mysql
    container_name: 3855_database
    environment:
      MYSQL_ROOT_PASSWORD: 28cjo$9*khgusj
      MYSQL_USER: Ian_admin
      MYSQL_PASSWORD: helpme
      MYSQL_DATABASE: 3855_project
    ports: 
      - "3306:3306"